version: '3.8'
# TEST COMMENT: Trigger PetClinic workflow only
# ANOTHER TEST COMMENT: Trigger PetClinic workflow and ZAP full scan
services:
  petclinic:
    image: springcommunity/spring-petclinic-rest
    container_name: petclinic
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m
